SELECT TRY_CAST(DDATE AS DATE) AS DDATE,
    SALESPERSON,
    CUSTOMERNAME,
    CARMAKE,
    CARMODEL,
    TRY_CAST(CARYEAR AS NUMBER) AS CARYEAR,
    SALEPRICE,
    COMMISSIONRATE,
    COMMISSIONEARNED
FROM {{ source("raw_bi_car", "CARSALES") }}
WHERE TRY_CAST(DDATE AS DATE) > '2020-01-01'